pipelines:
  default:
    - step:
        name: Sync GitHub Mirror
        image: alpine/git:latest
        clone:
          enabled: false
        script:
          - git clone --bare git@bitbucket.org:samplefirst1/webserver.git
          - cd webserver.git
          - git push --mirror git@github.com:PNikhilgowda/bittogit.git